broker: BROKER_ADDRESS
name: PC_NAME

sensors:
  - Cpu
  - CpuTemperatures
  - Ram
  - Os
  - DesktopEnvironment
  - Screenshot
  - Battery
  - Disk
  - Time

commands:
  - Lock
  - Reboot
  - Shutdown

values:
  DesktopEnvironment: DE_TO_FORCE
