broker: 192.168.1.233
name: LenovoYoga
update_rate: 20 # Seconds

sensors:
  - Cpu
  - CpuTemperatures
  - Ram
  - Os
  - DesktopEnvironment
  - Screenshot
  - Battery
  - Disk
  - Time
  - Brightness

commands:
  - Lock
  - Reboot
  - Shutdown
  - Brightness

