broker: 192.168.1.233
name: PcSenzaSchermo

sensors:
  - Cpu
  - CpuTemperatures
  - Ram
  - Os
  - DesktopEnvironment
  - Screenshot
  - Battery
  - Disk
  - Time

commands:
  - Lock

values:
  DesktopEnvironment: i3